### ISSUE TITLE
Unreadable book titles on dark theme (KDE/Linux)

### ISSUE THREAD

**Issue by offset-torque** [noembryo/KoHighlights#20]
On KDE desktop with default dark theme enabled, all text in the app inverts correctly except book titles, which stays black:

![kohighlights](https://user-images.githubusercontent.com/84420582/142007234-a1043a47-8923-4980-a744-1c53763f5e38.jpg)

**Comment by noembryo** [comment]
Interesting..
Do you use the pre-compiled version of KOHighlights or the Python script.
If it is the script, you could try to replace the `None` at the 964 line of `main.py` with `QApplication.palette().text().color()`.
Otherwise, since I only have a Xubuntu image for compiling the binaries and can't test your use case, you have to wait for the next release, to test if that fixes it...

**Comment by offset-torque** [comment]
I was using the binary. Tried Python version with your change and it worked. Thanks for the fix noembryo (also for the app itself).

**Comment by noembryo** [comment]
Fixed in 1.5.0.0

**Comment by offset-torque** [comment]
Working properly, thanks :+1:
