### ISSUE TITLE
Exporting to Markdown

### ISSUE THREAD

**Issue by AaronKnowls** [noembryo/KoHighlights#27]
First of all, thank you so much for developing this very useful software.

Just for your consideration, I would love to be able to export directly to markdown.

Thanks!

**Comment by noembryo** [comment]
There is no actual formatting stored in the `highlights` part of the book's metadata.
So, I can only save plain text.
OTOH, if you would prefer to format the exported file to markdown rather than html, that, I think it is easily added.

You can open a metadata file yourself (in a text editor) and see the data that are stored there.
If you find something of value, we can add it.. 😃

**Comment by noembryo** [comment]
Just checked the code and it seems a little complicated GUI-wise to select a fourth output format.
The whole thing needs restructuring, so it might take a while.

Until I do that, you can chip in any recommendations for the formatting of single-merged / multiple files exports.

**Comment by noembryo** [comment]
Added on [v.1.7.0.0](https://github.com/noembryo/KoHighlights/releases/tag/v1.7.0.0)..
