### ISSUE TITLE
Export/ to individual markdown files

### ISSUE THREAD

**Issue by vrmneto** [noembryo/KoHighlights#34]
I'm trying to export the highlights using the command "Export/ to individual markdown files", but all the highlights continue to go to a single file, regardless of the option I choose

any ideas?
![Captura de tela 2024-02-17 205420](https://github.com/noembryo/KoHighlights/assets/68965241/20f10653-217d-45c7-8a86-fc19c9cbc0c3)

**Comment by noembryo** [comment]
You are trying to export the highlights from a single book to different files?
If yes, then this is not possible.
The options to export to different files applies only to multiple books.
If you have selected multiple books, then you have the option to export the highlights of all the books in a single file or in different files.

If you are trying to do something else, please add some more details..

**Comment by vrmneto** [comment]
> Are you trying to export the highlights from a single book to different files? If yes, then this is not possible. The options to export to different files applies only to multiple books. If you have selected multiple books, then you have the option to export the highlights of all the books in a single file or in different files.

I was, but now it makes sense

thnx =)

**Comment by noembryo** [comment]
I'm partially responsible for your confusion, because the wording of the menu was not clear enough..
Next version will distinguish between the menu of the multiple selected books (which will stay as is) and the single book selection.
The later will be like this:
![menu](https://github.com/noembryo/KoHighlights/assets/24675403/c19ead9b-2ccd-4f44-9a61-b447b7cad069)

Thank you for bringing this to my attention.. 😃
