### ISSUE TITLE
Issues in v2.1.xx

### ISSUE THREAD

**Issue by edo-jan** [noembryo/KoHighlights#39]
Issue #1: Bookmarks view in Koreader incorrectly shows annotations after reverse sync
To replicate:
1. Use Highlights view in KH to delete a few annotations (but not the highlight). 
 2. Reverse sync the archved view back to the devices
 3. On the devices in the bookmarks the deleted annotations will show as blanks (see screenshot)
![Screenshot_20240827_081522](https://github.com/user-attachments/assets/adce29d6-5ffe-4ebd-aa1f-09284d85d63a)

**Comment by edo-jan** [comment]
Re: Issue 1 above: If the blank annotation is then opened on the device - it will show no characters in it. If one applies "save" then the blank pensil is replaced with the underlying highlight text (the expected)

**Comment by noembryo** [comment]
> 1. Use Highlights view in KH to delete a few annotations (but not the highlight).

I think that you have misunderstood some of the terms we're using, and that leads to my confusion about what is happening.
I'll try to clarify some meanings.
* Bookmark: the info about a page of a book (shows a dogear at the top right of the page, not seen inside KOHighlights)
* Highlight: the info about a part of a text in a book (highlighted on the reader, can be deleted from within KOHighlights)
* Comment/Note: info about a highlight (can be edited/deleted within KOHighlights)
* Annotation: either a Highlight or a Bookmark (the key that all highlights and bookmarks are stored in the "new" metadata is called "annotations")

To make things more complicated, KOReder has only one place to access highlights and bookmarks, and it's called "Bookmarks".

So, in light of all this, you have to explain to me again how you can delete a few annotations but not the highlight, because I don't believe it's possible.
Try to be more specific with all the steps..

Also keep in mind that this is the last day with my PC, and after this, it will be a while until I can work in this again..

**Comment by edo-jan** [comment]
> So, in light of all this, you have to explain to me again how you can delete a few annotations but not the highlight, because I don't believe it's possible. Try to be more specific with all the steps..
> 

In light of the clarification provided, I deleted Comments/notes associated with highlights. For context, a while back there was a weird bug in Koreader (got fixed eventually) which created Comments/Notes on blank highlights. Essentually, it would put the text of the highlight into the comment/note. These "notes" I manually deleted from KH. and synced it back to the devices. The result you see on the screenshot above.

> Also keep in mind that this is the last day with my PC, and after this, it will be a while until I can work in this again..

Noted. For how long are you going to be away?

**Comment by noembryo** [comment]
OK, see the problem now.
I can fix it before I leave..
> For how long are you going to be away?

Not sure, depends. From a couple of weeks to a month?

**Comment by noembryo** [comment]
Fixed in [v2.1.1.0](https://github.com/noembryo/KoHighlights/releases/tag/v2.1.1.0)..
