### ISSUE TITLE
Unable to run KoHighlights on Ubuntu

### ISSUE THREAD

**Issue by czar** [noembryo/KoHighlights#42]
Since the v2 releases, I haven't been able to run KoHighlights on Ubuntu due to an error. I was using an older version before, but now it seems that this version no longer processes highlights from the latest KoReader update. :( Could you advise me on how to run the newest version of KoHighlights or access highlights with the older version? Any help would be greatly appreciated. Thank you!

./KoHighlights.v2.1.1.0 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

(KoHighlights.v2.1.1.0:293444): GLib-GIO-ERROR **: 22:09:50.642: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap

**Comment by noembryo** [comment]
Unfortunately this seems like an Ubuntu error and not a Python one.
My knowledge of Linux is limited to keeping an image of old Xubuntu just to compile the Linux version.
Maybe there is a compatibility problem between OS versions.

The highlights format of KOReader changed in the latest versions, so the only way to see them in KOHighlights, is by using the newer versions.

I'll be away from my PC for a couple of weeks more, but I'll try to investigate some more when I'll be back..

**Comment by rhsanborn** [comment]
Thanks for the update. I'm able to get it running with Python 3.8.20. It segfaults with 3.12. I haven't had time to dig into it much more to figure out where it's dying and which version actually broke it.

**Comment by noembryo** [comment]
Can you please try [this version](https://mega.nz/file/Dc8SCC5A#5mDWjeQrOkUaI3mBFjUF7Ehdui_ue59eafGvjnmIKhk) that is compiled using a newer version of PyInstaller..

**Comment by czar** [comment]
> Can you please try 

Thanks yet I still get the following error

```
"(KoHighlights:1450886): GLib-GIO-ERROR **: 20:21:44.463: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap"
```

**Comment by noembryo** [comment]
So, no change at all..
Unfortunately, since I don't really know anything about Linux, I don't believe I'll mange to solve this.. 😞

**Comment by rhsanborn** [comment]
czar, what version of Ubuntu are you running? I may try to spin up a VM and see if I can recreate some of these errors.

**Comment by czar** [comment]
> czar, what version of Ubuntu are you running? I may try to spin up a VM and see if I can recreate some of these errors.

Thanks.  Currently on 22.04.05 LTS.

**Comment by noembryo** [comment]
Can you please try another idea?

- Open a terminal and type `QT_QPA_PLATFORM="wayland;xcb` and enter
- Then, drop the KOHighlights executable on the same terminal and press enter..

If there are error, please post them here.

**Comment by noembryo** [comment]
Also, if that doesn't work, try it with `QT_QPA_PLATFORM="wayland"`

**Comment by noembryo** [comment]
> Take these with a bucket of salt. I'm not running either Gnome or KDE. I'm running Sway on Arch. So I have a bit of a weird environment. I'm going to try to spin up a Fedora VM with Gnome to see how it behaves. That will be Wayland and will be more typical.

Hmm.. Don't know much about the flavors, but worth a try anyway.. 🤷‍♂️

**Comment by rhsanborn** [comment]
Here it is from Fedora 40 with Gnome:

rhsanborn@fedora:~/Downloads$ ./KoHighlights 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
GLib-GIO-Message: 11:21:59.450: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(KoHighlights:39288): GLib-GIO-ERROR **: 11:21:59.451: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)
rhsanborn@fedora:~/Downloads$ QT_QPA_PLATFORM="wayland;xcb"
rhsanborn@fedora:~/Downloads$ ./KoHighlights 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
GLib-GIO-Message: 11:22:53.730: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(KoHighlights:39368): GLib-GIO-ERROR **: 11:22:53.730: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)
rhsanborn@fedora:~/Downloads$ QT_QPA_PLATFORM="wayland"
rhsanborn@fedora:~/Downloads$ ./KoHighlights 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
GLib-GIO-Message: 11:23:12.571: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(KoHighlights:39411): GLib-GIO-ERROR **: 11:23:12.572: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)

**Comment by noembryo** [comment]
I wonder if you can to check `QT_QPA_PLATFORM=wayland` (without the quotes) too. Just in case..

**Comment by rhsanborn** [comment]
With and without quotes, it all works the same. One interesting thing is if I execute the executable with sudo, it launches ...

**Comment by noembryo** [comment]
> One interesting thing is if I execute the executable with sudo, it launches

Hmm..
This _is_ a way out I think..

**Comment by rhsanborn** [comment]
Do you have a quick document that shows how you compile the binary? I'd like to try compiling from  Wayland native system and see if it behaves at all...

**Comment by noembryo** [comment]
Pyinstaller using the `KoHighlights.spec` that's inside this [KoHighlights.zip](https://github.com/user-attachments/files/17651167/KoHighlights.zip) and running `/home/x/.local/bin/pyinstaller -y KoHighlights.spec`

**Comment by rhsanborn** [comment]
Sorry for the (long) delay. ...Holidays. 

I've setup a fairly basic Fedora 41 workstation, running KDE. It's running Wayland. Python version is 3.13.1.

I downloaded the PySide6 version of KoHighlights, I pip installed:
- Pyside6
- requests
- bs4
- packaging
- pyinstaller

I ran pyinstaller with your spec file, and it runs great.

Almost all the Linux distributions are shipping with Wayland now instead of X11. I'm really curious if an executable built on a Wayland native system would run on X11 systems. Maybe your PySide6 change coupled with just updating the build process to use a Wayland-native Linux distribution would fix these issues?

**Comment by noembryo** [comment]
> Almost all the Linux distributions are shipping with Wayland now instead of X11. I'm really curious if an executable built on a Wayland native system would run on X11 systems. Maybe your PySide6 change coupled with just updating the build process to use a Wayland-native Linux distribution would fix these issues?

I don't think that the problem is PySide6 vs the PySide2.
As you said, the problem with the compiled binary most probably has to do with the distribution environment.
I use an older Xubuntu image to keep as much compatibility as I can, since I read that the newer versions would be compatible.
Though whatever I compile with it, doesn't run on some newer systems (the Linux backwards compatibility was too good to be true)..
Unfortunately, since I know next to nothing about Linux, I can't investigate much more.. 😞

**Comment by noembryo** [comment]
@rhsanborn, @czar Can you please check [this post](https://github.com/noembryo/KoHighlights/issues/50#issuecomment-2562002034) to see if the already compiled [KOHighlights binary](https://github.com/noembryo/KoHighlights/releases/download/v2.3.0.0/KoHighlights.v2.3.0.0.linux.x64.tar.gz) runs on your system?

**Comment by rhsanborn** [comment]
Your binary works on Fedora but only if I 'export QT_QPA_PLATFORM=xcb' first. That makes sense. That's telling the system that this should be run as an X11 app, not Wayland. 

On a lark, I spun up a VM running Ubuntu 18.04. My thesis is that if KoHighlights is compiled on a machine that doesn't know about Wayland, then those things aren't being compiled in. That machine is running Python 3.6.9, I installed the requirements, installed Qt5, and compiled it. It runs on itself, Debian 12, and Fedora 41.

**Comment by noembryo** [comment]
You mean that this binary runs on your systems but mine doesn't?
This is strange, since my Xubuntu image version is also 18.04 and its Python version is 3.6.9..
I don't understand why my binary doesn't work on your system.
What could be the difference?

**Comment by rhsanborn** [comment]
Your binary doesn't run on my system without me telling it to run like it's running in X11 first. Whereas if I compile it on Ubuntu 18.04 it seems to run pretty globally.

I'm going to try to download and install Xubuntu 18.04 and check this assumption. I think Xfce took a while to switch to Wayland. I think it kept running X11 for a long time. My guess is that your Xubuntu 18.04 install is using X11 and doesn't have Wayland installed. I think my Ubuntu 18.04 install has Gnome and has Wayland by default, so it has all the extra code for Wayland. Now that all our desktop installs are flipping to Wayland, I think that's why we're hitting issues.

**Comment by noembryo** [comment]
Hmm, this is interesting.
Is there a way to install Wayland in Xubuntu?
If not, then, do I have to create a second image with Ubuntu and build two different binaries, one for X11 and one for Wayland?

**Comment by rhsanborn** [comment]
So, I'm a minimally educated idiot, so take this with a grain of salt. 

I'm spinning up a Xubuntu instance right now to validate everything I said above. I'll also test if the binary I compiled with Wayland support will run on this Xubuntu instance. I think it will. In that case, I would just not build with the Xubuntu instance. I'd spin up a VM with Wayland support like Ubuntu 18.04. I'm sure there is a way to add Wayland, I can't say the right way to do it though.

**Comment by rhsanborn** [comment]
So, this is the only outcome I wasn't prepared for, the binary I compiled on the Xubuntu 18.04 VM I just spun up ... works fine on my Fedora 41 box. It runs exactly the same as the Ubuntu binary I compiled. 

I don't want to send you down a rabbit hole since I'm a big dumb ape, but there are two interesting things I'd pursue next:

1) 
- It looks like Qt 5.11 is the first version to include the Wayland targets by default.
https://stackoverflow.com/questions/50243841/running-qt-application-under-wayland
- I think there have been instances where there were version mismatches between the system Qt libraries and what pyinstaller wants to use.
https://github.com/pyinstaller/pyinstaller/issues/7506

2) Any chance you have a stale build VM that just needs to be rebuilt?

Finally, I love this tool so much, it's critical to my reading workflow now. I'm willing we can all just figure out how to run it with Python instead of needing the binary if we need to. :-)

**Comment by noembryo** [comment]
> I'm willing we can all just figure out how to run it with Python instead of needing the binary if we need to. :-)

But, you can do this already with either PySide2 or PySide6..

> Any chance you have a stale build VM that just needs to be rebuilt?

I can copy the current one and try to update, or I can download another one if you know one that can work.
I do like the Xubuntu, because I can't really work with the newer versions of Gnome (I tried a couple of times, a few years back, and it was really frustrating 😡)

I don't need it for anything other than building the app.
Just to be compatible with VMWare 12.1.1 Workstation that I'm using..
