### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by edo-jan** [noembryo/KoHighlights#45]
Here is a draft version of the user guide. Let me know if you have any suggestions. I am not sure about the format so I just post it here as a word document. 
[KH user guide.docx](https://github.com/user-attachments/files/17454751/KH.user.guide.docx)

**Comment by noembryo** [comment]
Great work!! 🙏 
Thank you for your time.
There are a lot of suggestions in there, that we have to discuss somewhere (maybe I'll put them numbered here and reference each one separately).

A lot of info here (nice to see another view for something you know from a different perspective).
I think that the best format for it is (guess what... 😉) markdown (!), since it will be hosted on GitHub..
I converted the `.docx` to `.md` [KOHighlights User Guide.zip](https://github.com/user-attachments/files/17462252/KOHighlights.User.Guide.zip)

It needs some more work, and some things might have to be said a little differently, but for now it's a solid base.
I'll try to find some free time to upload a revised version soon.
Please wait for it before doing any more work, since it might lead us into two different versions that we'll then have to sync.. 😉 

Another thing to mention is that unfortunately, the screenshots that you took does not have the default look of the app, and that might be confusing for some users.
Or maybe not, since the readme file's screenshots have two different versions of the app, so..

**Comment by noembryo** [comment]
> 1. Re-arrange the groups on the toolbar to appear from left to right to align with the typical workflow.

No real reason for the way it is. This is a pattern I use with all my programs.
It is just aesthetics.
I keep the tools that are more static to the right.
It's also has to do with the evolution of the app.
In the beginning there were no right buttons, since the Books view was the _only_ view.
Later the Highlights view was added and I didn't want to move the previous buttons somewhere else.
Then the Archived mode was introduced, etc..
> 2. Rename "Loaded" button into "Devices"

Loaded means "Loaded Books".
These can be the books from a specific device of course, but you can also add (with drug and drop) a folder with books from another device, and also a single book that exists only in your hard drive.
> 3. Create tabs on the Preferences dialog to group the functionality into several categories: Appearance, Annotation Options.
>    Under the Annotation Options consider "Advanced" button for Custom Markdown features

I would do that if there were a few more "Appearance" options.
As it is now, almost all the options are for the Highlights, so maybe in the future.
> 4. Allow select and copy of the highlights.
>    When commenting it is very common to start with a copied highlight text which then can be paraphrased, cited, or otherwise illustrated by the user while making the comment.

This is already implemented both in Books and Highlights view.
> 5. If the Books view is selected - only make available "Filter book titles" option

We can currently use the filter with words that exist in the Highlights and their Comments too.
Why remove these extra options?
> 6. Hide "Delete" button from the main menu as there is a very high potential for new users to causing significant damage such as inadvertently deleting entire books / metadata files or both.

When pressing this button and explicitly select an action, a warning dialog is displayed that describes what is going to happen.
If the user agrees to it, then, they know what they doing.
No reason to dumb down the app.
> 7. Make the "Clear List" button to clear the selected books if one doesn't want to clear the entire list, but only wants to clear the selected books

Since "Clear List" means clear *all* the list's items, the current action is working as it should.
But, what I *should* do, and thanks for the reminder, is to assign the Del button to remove the selected items from the list (and not delete them from the storage, as it is now.. 🙄)
> 8. Rename "Highlights" button into "Grid view" to more accurately describe the function.

I don't think that "Grid view" is more descriptive than "Highlights".
The reason I named it like this, is literal.
In the first View we are looking at the Books (the main, bigger panel), and in the second View we are looking at the Highlights. 😃 
> 9. Remove Merge/Sync action button from Books view even though it might have limited application in some case. However, it is more confusing than useful now, given that we have a separate Sync Groups View with full sync functionality.

This is something that exist also in the right click menu, and has some functionality that is missing from the Sync Groups (e.g. sync with a specific file).
Granted, it's less useful now than it used to be, but to remove it..
I'll think more about it.
> 10. Allow double clicking on any field to open a comment for editing (currently one must double click specifically on the "Comment" field or the annotation will not open for editing.)

Double clicking the Title and getting an empty dialog, might make the user think that they can edit the Title.
OTOH, looking at the right click menu to check  the existing options, I noticed that the action to edit the comment was named "Comments" and not "Edit Comment" as it should, so here comes another fix.
I'll think more about the double click action, but I'm leaning more on keeping it as it is.
We'll see.
> 11. Option to wrap the highlight / comment text. Currently, long highlights / comments cannot be viewed fully as they are limited by the column's width.

The problem with that is that it will make the rows of the Highlights table have huge height, and that will make it really ugly (e.g. having a very big box that contains only a page number, etc.)
We can always see the whole highlight by hovering the mouse over it, and letting the tooltip gets displayed..
> 12. Change "Merge Highlights" checkbox to "Merge Annotations" for consistency of terminology

Actually, I think we should go the other way, since the app is called KO***Highlights***.
> 13. Change "Copy Archived to Group" with "Replace with archived"

I'm not really satisfied with any of them.
The meaning of the action is displayed as a tooltip and its "Copy the archived version to all Sync group items", but unfortunately its very big for the button.
More thinking is needed.

**Comment by edo-jan** [comment]
> Great work!! 🙏
> Thank you for your time.

My pleasure. Glad to contribute to your great app.

> > 1. Re-arrange the groups on the toolbar to appear from left to right to align with the typical workflow.
> 
> No real reason for the way it is. This is a pattern I use with all my programs. It is just aesthetics. I keep the tools that are more static to the right. It's also has to do with the evolution of the app. In the beginning there were no right buttons, since the Books view was the _only_ view. Later the Highlights view was added and I didn't want to move the previous buttons somewhere else. Then the Archived mode was introduced, etc..

I suspected this to b e the case. Most tools do evolve over time and then it helps to have a fresh pair of eyes who would take a different perspective - e.g. as a new user who has no experience with the product.   It would help to rethink the interface given what the product has evolved into.  

> > 3\. Rename "Loaded" button into "Devices"
> 
> Loaded means "Loaded Books". These can be the books from a specific device of course, but you can also add (with drug and drop) a folder with books from another device, and also a single book that exists only in your hard drive.

I understand it perfectly, it is the new users who would likely be puzzled with it... 🤩 


> > 4\. Allow select and copy of the highlights.
> >     When commenting it is very common to start with a copied highlight text which then can be paraphrased, cited, or otherwise illustrated by the user while making the comment.
> 
> This is already implemented both in Books and Highlights view.

Hmm... in what version? I am in 2.2.2.1 and I am still unable to do this


> > 5\. If the Books view is selected - only make available "Filter book titles" option
> 
> We can currently use the filter with words that exist in the Highlights and their Comments too. Why remove these extra options?

Imho,  because this finds the book, not the highlights and not comments promised by the dialog.  


> > 6\. Hide "Delete" button from the main menu as there is a very high potential for new users to causing significant damage such as inadvertently deleting entire books / metadata files or both.
> 
> When pressing this button and explicitly select an action, a warning dialog is displayed that describes what is going to happen. If the user agrees to it, then, they know what they doing. No reason to dumb down the app.

As mentioned, I find this to be the most dangerous feature that invites a fiasco with some unsuspecting user... If you insist for it to remain, we should consider adding some backup functionality in 3x. I will create a separate enhancement request for this as I have been thinking about it for a while. 



> > 7\. Make the "Clear List" button to clear the selected books if one doesn't want to clear the entire list, but only wants to clear the selected books
> 
> Since "Clear List" means clear _all_ the list's items, the current action is working as it should. But, what I _should_ do, and thanks for the reminder, is to assign the Del button to remove the selected items from the list (and not delete them from the storage, as it is now.. 🙄)

That will do the trick! Thank you.


> > 8\. Rename "Highlights" button into "Grid view" to more accurately describe the function.
> 
> I don't think that "Grid view" is more descriptive than "Highlights". The reason I named it like this, is literal. In the first View we are looking at the Books (the main, bigger panel), and in the second View we are looking at the Highlights. 😃

"Grid view" is absolutely a lot more descriptive... 😃  

> More thinking is needed.

With this I should unequivocally agree ! 😎

**Comment by noembryo** [comment]
> It would help to rethink the interface given what the product has evolved into.

You have a point there.
I'll re-arrange them to see how it looks, and then decide..
>I understand it perfectly, it is the new users who would likely be puzzled with it... 🤩

I know.. 😜 
I was just explaining why I think that the term "Devices" was not a fitting one..
> > > 4. Allow select and copy of the highlights.
> > 
> > This is already implemented both in Books and Highlights view.
> 
> Hmm... in what version? I am in 2.2.2.1 and I am still unable to do this

Maybe I didn't understand what you are asking?
I thought you were asking about a way to copy the highlighted text.
You can do this by right clicking any highlight or highlights in Books view and select "Copy" or in Highlights view and select "Copy Highlights"
In Books view you get more than just the Highlighted text, but you can delete what you don't need.
.. or you meant something else?
> > > 5. If the Books view is selected - only make available "Filter book titles" option
> > 
> > We can currently use the filter with words that exist in the Highlights and their Comments too. Why remove these extra options?
> 
> Imho, because this finds the book, not the highlights and not comments promised by the dialog.

But it filters the books that contain that word in the Highlight (or the Comments).
How else can you achieve this?
And remember, it isn't a Search/Find function. 
It's a Filter that filters what is visible in the Books view..
>As mentioned, I find this to be the most dangerous feature that invites a fiasco with some unsuspecting user...

There is not a single "DELETE" function, in any app, that is not dangerous..
And that's why there are warnings before actually delete anything.
But that said, I want to have a way to actually delete something.
If the user just presses buttons without reading what it is they press, then they are not "unsuspecting", they have other problems that can't be handled by this app. 🤷‍♂️

**Comment by edo-jan** [comment]
> There is not a single "DELETE" function, in any app, that is not dangerous..
> And that's why there are warnings before actually delete anything.
> But that said, I want to have a way to actually delete something.
> If the user just presses buttons without reading what it is they press, then they are not "unsuspecting", they have other problems that can't be handled by this app. 🤷‍♂️

I hear you. Perhaps we could then come up with a better submenu items for the Delete button? E.g. consider changing "Selected book info" into "Delete book's metadata file";   "Selected book" - to "Delete selected book's epub file"; and  "All missing book info" into "Delete metadata files for all missing books"

**Comment by edo-jan** [comment]
> > > > 7\. Allow select and copy of the highlights.
> > > 
> > > 
> > > This is already implemented both in Books and Highlights view.
> > 
> > 
> > Hmm... in what version? I am in 2.2.2.1 and I am still unable to do this
> 
> Maybe I didn't understand what you are asking? I thought you were asking about a way to copy the highlighted text. You can do this by right clicking any highlight or highlights in Books view and select "Copy" or in Highlights view and select "Copy Highlights" In Books view you get more than just the Highlighted text, but you can delete what you don't need. .. or you meant something else?

I meant using the mouse to select some (relevant) portion of the highlight and then pasting it into the comment field.  This would be a lot more useable rather than using the right-click / copy / paste and then cleaning it out. I know the feature is kind of there. But this would be an improvement

**Comment by edo-jan** [comment]
Btw, when I open several books in the Highlights view (some of my books have tons of comments) the grid becomes very unresponsive.  The program appears to freeze (it keeps working in fact) when I attempt to activate the sort feature on the columns. Not sure if this would qualify as an enhancement request

**Comment by noembryo** [comment]
> consider changing "Selected book info" into "Delete book's metadata file"; "Selected book" - to "Delete selected book's epub file"; and "All missing book info" into "Delete metadata files for all missing books"

But, this is almost exactly what the warning dialog says _before_ doing anything.
The main difference is that in the warnings, the Metadata are called Information.
> I meant using the mouse to select some (relevant) portion of the highlight and then pasting it into the comment field. This would be a lot more useable rather than using the right-click / copy / paste and then cleaning it out.

😄 You're more lazy than me.. 😜 
> Btw, when I open several books in the Highlights view (some of my books have tons of comments) the grid becomes very unresponsive. The program appears to freeze (it keeps working in fact) when I attempt to activate the sort feature on the columns.

Sorting of many items might take a lot of processing..
I don't think I can optimize it more..

**Comment by edo-jan** [comment]
> > I meant using the mouse to select some (relevant) portion of the highlight and then pasting it into the comment field. This would be a lot more useable rather than using the right-click / copy / paste and then cleaning it out.
> 
> 😄 You're more lazy than me.. 😜

I certainly am ...😃 also a big fun of what is known as "user-friendly"

**Comment by noembryo** [comment]
Made some additions/changes/revisions on the KOHighlights User Guide.
[KOHighlights User Guide.zip](https://github.com/user-attachments/files/17578996/KOHighlights.User.Guide.zip)

**Comment by noembryo** [comment]
https://noembryo.github.io/KoHighlights/
Not officially linked to the 1st page readme yet, since there are some features described that are not yet available with the latest release.

**Comment by noembryo** [comment]
Also, can you please double-check the `lua` code (for the user patch), because I don't trust the .docx format that much.
It may have mangle it somehow..

**Comment by edo-jan** [comment]
Great work with the guide!  The annotated screenshot showing the color version of the skin are excellent as well (it looks like you also used Faststone capture tool 😀.   I am sure the guide will be welcomed by the community as well as attract a lot of new users.
Having said that I still believe that some of the current notations should be changed to more descriptive ones (and I am not saying that the terms I proposed are any better, I am just saying that we should take some serious thought on how to make it more intuitive and foolproof.  Maybe in version 3x? 

You are correct to suspect the MS word when it comes to code - there are a couple of extra slashes in the version of your guide. I am attaching the text file with the correct version. 
[2-save-full-chapter-path.lua.txt.zip](https://github.com/user-attachments/files/17594140/2-save-full-chapter-path.lua.txt.zip)

**Comment by noembryo** [comment]
> The annotated screenshot showing the color version of the skin are excellent as well (it looks like you also used Faststone capture tool

I used Photoshop for those..
> I am just saying that we should take some serious thought on how to make it more intuitive and foolproof.

Any suggestion is welcomed as you know..
Not guarantee that it will be done, but I 'll seriously consider any interesting idea..😉 
> I am attaching the text file with the correct version.

Thanks, I'll fix that ASAP.

**Comment by edo-jan** [comment]
Typo in [https://noembryo.github.io/KoHighlights/#deleting-highlights](url)
3. When KH displays a warning **lick** “Yes” to proceed and “No” to cancel

**Comment by edo-jan** [comment]
Suggestion: make all warnings in red

**Comment by noembryo** [comment]
> Typo in [Deleting highlights](https://noembryo.github.io/KoHighlights/#deleting-highlights)
> 3. When KH displays a warning **lick** “Yes” to proceed and “No” to cancel

👍 
> Suggestion: make all warnings in red

I'm trying to avoid using html code and I don't know a pure markdown way to change the color..

**Comment by noembryo** [comment]
The guide went public.
Thank you! 🙏

**Comment by edo-jan** [comment]
🙏

**Comment by edo-jan** [comment]
I am thinking maybe it would be a good idea to create a couple of posts in the mobilereads forum describing "how I use KH to synchronize across my devices" or something like this. Just in the way of generating some awareness that this tool exists and what one can do with it.

**Comment by edo-jan** [comment]
Check this out [ https://www.mobileread.com/forums/showthread.php?p=4465295#post4465295](url)

**Comment by noembryo** [comment]
Wow! That was fast.. 😉 
Thank you for this. 🙏 
I have never used Syncthing (that's why I didn't include the initial info in the user guide), so I didn't know all that stuff about its usage.
Very interesting..

BTW, I don't know if you have already read the discussion on GitHub, but I was talking to a KOReader dev that told me that the problem of the out of sync pages is more or less solved.
Here is how:
At first, while syncing in KOHighlights, the app tries to compute the relative place of the page in the synced book and it's close enough, not to change the order of the pages that much.
But irrelevant to that, after the sync, KOHighlights activates a flag in the metadata that tells KOReader that the pages need to be recalculated.
So, at the next opening of the book, KOReader recalculates all the pages and the numbers are accurate once more.

Also, you misspelled my username.. 😜

**Comment by edo-jan** [comment]
> BTW, I don't know if you have already read the discussion on GitHub, but I was talking to a KOReader dev that told me that the problem of the out of sync pages is more or less solved. Here is how: At first, while syncing in KOHighlights, the app tries to compute the relative place of the page in the synced book and it's close enough, not to change the order of the pages that much. But irrelevant to that, after the sync, KOHighlights activates a flag in the metadata that tells KOReader that the pages need to be recalculated. So, at the next opening of the book, KOReader recalculates all the pages and the numbers are accurate once more.
> 
Not sure I ever heard about the problem in the first place... do you have a link for more info?

> Also, you misspelled my username.. 😜
Fixed 😎

**Comment by noembryo** [comment]
> Not sure I ever heard about the problem in the first place... do you have a link for more info?

Unfortunately, no links that I can remember..

**Comment by noembryo** [comment]
#38 😃

**Comment by edo-jan** [comment]
A small change to improve readability. 
![2024-11-05_121036](https://github.com/user-attachments/assets/cf884859-ddff-4655-a1e4-622794b41444)

**Comment by noembryo** [comment]
Hmm.. OK.. 😉

**Comment by edo-jan** [comment]
Do you think we should add the info on "logical pages" user patch to the advanced section? This makes a big difference in the merged outcome

**Comment by noembryo** [comment]
> Do you think we should add the info on "logical pages" user patch to the advanced section? This makes a big difference in the merged outcome

What is the "merged outcome"?
Also, I think that adding a lot of KOReader patches code and explanations will make the guide more daunting for the first time user that reads it.
My opinion is that we keep the relevant parts (with a brief explanation of the feature) on the advanced section, and link to the detailed explanations and code somewhere else.
Perhaps on a post of a MobileRead or an extra file here..

**Comment by noembryo** [comment]
Some day these patches might make it to the normal KOReader release, and then we can add some more info about them..
