### ISSUE TITLE
I can't get KoHighlights to run at all

### ISSUE THREAD

**Issue by auspiciouslink** [noembryo/KoHighlights#49]
I'm so sorry for creating a new issue for this because I'm like 99.999% sure this is a PEBCAK error, but I cannot for the life of me figure out how to get this running on Ubuntu. Or if it's not supposed to run on Ubuntu, I can't figure out how to install it as a plugin in KOReader on any of my other devices.

I've tried reading your new User Guide, but it starts from when the program is already open and running, and I can't get that far. I have the tarball. I've unzipped it. I've tried modifying it to run. I've tried every single thing I can think of that I've used to run anything else on Linux in the past, and I just can't get it to *do* anything!

Would you consider adding a section in the User Guide about how to get it up and running? It'd even be great if it linked to instructions that might exist somewhere else. I just can't figure out where to start!

Thanks so much for building this, and reading this, and again, sorry for being such a n00b.

**Comment by noembryo** [comment]
Unfortunately, since I'm on Windows, my knowledge of Linux is non-existent..
I just keep a Linux image somewhere just for the builds.
It's an old Xubuntu 18.04 image, to be compatible with many versions.

But lately, something must changed to Ubuntu and some people can't run the app anymore (see #40 and #42).
Until someone knowledgeable steps in, there is nothing I can think, other than run the app from the code.

This is not that difficult if you have Python 3.6 or later in your system and all [the dependencies](https://github.com/noembryo/KoHighlights#dependencies) installed.
You just clone/download the repository, open a terminal inside the directory and run `python main.py` or `python3 main.py`

**Comment by noembryo** [comment]
Let's try something more..
Can you please open a terminal, drag the KOHighights app to it, press enter and post here the errors that you get?

**Comment by auspiciouslink** [comment]
This may have helped me sort out the problem in a roundabout way.

When you said "drag the KOHighlights app to it," I'm wasn't sure what you meant. I don't have anything on my end that I can identify as an app. I could drag the extracted tarball to it? All that does is print the path and tell me it's a directory.

But I tried running main.py, thinking maybe that was what you meant, and as soon as I got PySide2 installed, it started right up!

So I'm going to return to apologizing for being an absolute doofus and not figuring this out sooner. Thanks so much for pointing me in the right direction!

**Comment by noembryo** [comment]
> When you said "drag the KOHighlights app to it," I'm wasn't sure what you meant. I don't have anything on my end that I can identify as an app

Then, the things are even better than I thought.. 🍾 
The tar contains a KOHighlights binary, that you have to extract from the archive (the tar.gz file).
Once extracted, you left with this KOHighlights file, that you can run by double clicking on it.. 😃
