### ISSUE TITLE
Sorting of books titles doesn't ignore A & The

### ISSUE THREAD

**Issue by richo67** [noembryo/KoHighlights#5]
Hello again ;-)
I am using KoHighlights very very often, one ting is that sorting on book title is different then in KOReader and in Calibre too. This makes the certain action a bit difficult.

Would it be possible to make sorting to ignore the A & The part of title? This would make it same in all three programs.

**Comment by noembryo** [comment]
I'm glad that you find KoHighlights useful :o)

As for the sorting, I'm not sure that KoReader sorts things like that.
Just checked mine (using "Detailed list with metadata, no images) and it wasn't.
Maybe the problem starts with Calibre's default settings, that write the metadata like "Title of book, The", and Koreader just sorts by the metadata that finds in the books.

Because of the problems of this type of sorting (metadata/filenames mismatch), I changed a setting somewhere in Calibre many years ago and the sorting is the same in all three programs.
A quick search returned [this](https://www.mobileread.com/forums/showpost.php?s=c888096832c72d6269024b9cf5a95bde&p=3813369&postcount=3), but I don't really remember.

Anyway, I'll think about it today and try to find a way to add it without creating a new "Preferences" section..
The main problem is that from tomorrow afternoon I'm on holidays without a PC, so if nothing new happens by then, it will have to wait a while..

**Comment by noembryo** [comment]
OK, I added this.
The way to do it, is: Right click the "Title" header and select the `Ignore "A" & "The"` entry.
It will be on the next release later today..

If you have any other fast suggestions you have some hours before I upload the new binaries.. ;o)

**Comment by richo67** [comment]
Thank you a lot, it is great to have such a active development ;-) 

Calibre storing file of the book with the The and A as you described yourself in format "Title of book, The", koreader however put in lua file the title in format The Title of book. KoHighlights read the lua I suppose and using that to display title of the book.

Great that feature to merge highlights with archived version, this is great feature not to lose my highlights! Thank you again very much for all your work and effort.

Enjoy your holiday.

**Comment by richo67** [comment]
I wished you to enjoy your holiday and here I am again to bug you. Please feel free to ignore this during your holiday. I only wanted to know you that somethings not fully right with that sorting. Please see the attached picture. Not sure how that first book got there. I selected to ignore "The & A" _(Maybe also An should included ;-)  should we call then "English articles" ? )_ 

![ScreenClip](https://user-images.githubusercontent.com/9590148/63633945-97531a80-c650-11e9-9ca4-08227660bd0d.png)

**Comment by noembryo** [comment]
Ooops, sorry, my bad!! :o)
Fixed it and uploaded it...

**Comment by richo67** [comment]
Thanks!

**Comment by noembryo** [comment]
Just saw your edit about the extra "An"...
Well, I'll add this too, but do you think there is anyone else missing? ;o)

**Comment by noembryo** [comment]
Updated..

**Comment by richo67** [comment]
YOU are amazing!

> Just saw your edit about the extra "An"...
> Well, I'll add this too, but do you think there is anyone else missing? ;o)

There is no more in English articles only A, An, The So this is done great that you made it an options ;-)

Enjoy your holiday. You have another beer/wine (insert your favorite drink) on me. 
-r-

**Comment by noembryo** [comment]
You are spoiling me ;o)
Thanks. Cheers!

On August 25, 2019 8:40:13 AM GMT+03:00, richo67 <notifications@github.com> wrote:
>YOU are amazing!
>
>> Just saw your edit about the extra "An"...
>> Well, I'll add this too, but do you think there is anyone else
>missing? ;o)
>
>There is no more in English articles only A, An, The So this is done
>great that you made it an options ;-)
>
>Enjoy your holiday. You have another beer/wine (insert your favorite
>drink) on me. 
>-r-
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/noembryo/KoHighlights/issues/5#issuecomment-524602254

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
