### ISSUE TITLE
Add option to sync deletion

### ISSUE THREAD

**Issue by righteous-coder** [noembryo/KoHighlights#51]
## Current behavior

1. You sync device A and device B
2. On device A, you delete one of the highlights
3. You sync device A and device B again
4. The deleted highlight is restored on both devices

## Desired behavior

I don't want deleted highlights to be restored like this. So I'd like an option to sync deletions themselves.

I think this can be done by recording the last sync time and then checking if highlights older than that exist on all devices.

It'd be nice to also show a pop up dialogue that lists all highlights to be deleted.

Thank you.

**Comment by noembryo** [comment]
There is no way I can think of, to detect what missing highlights we want to sync and what we don't.
I don't like the idea of relying to the dates for that, since this can create more problems than it solves.
Currently this problem has a workaround [here](https://noembryo.github.io/KoHighlights/#deleting-highlights).
Perhaps this is enough for a feature that is not used that often..

**Comment by righteous-coder** [comment]
That's fair. I'll try that workaround, thanks.
