### ISSUE TITLE
Installation Issues with KOhighlights

### ISSUE THREAD

**Issue by anoop249** [noembryo/KoHighlights#53]
Hi, 

I have a newly purchased Kobo Libra Color device. 

I tried to install KOhighlights application on my laptop PC that has Windows 11 OS. I have AVASTOne internet security installed on the laptop. 

I encountered some issues when trying to install the KOhighlights on my laptop PC. 

Attached to this post is a screenshot showing what issues I had encountered. 

It seems Windows instantly recognizes the KOhighlights .exe setup file as a threat and also AVAST anti-virus scan instantly also recognizes the .exe setup file as a threat and instantly removes the .exe setup file from my hard drive and quarantines it. 

Please assist on this issue encountered, thank you. 

![KOhighlights installation issue](https://github.com/user-attachments/assets/e7c3fd9d-f6bd-4dfa-a0c6-3e7df701c1b1)

**Comment by noembryo** [comment]
> It seems Windows instantly recognizes the KOhighlights .exe setup file as a threat and also AVAST anti-virus scan instantly also recognizes the .exe setup file as a threat and instantly removes the .exe setup file from my hard drive and quarantines it.

Actually, things are not exactly like this.
Only Avast "recognize" the setup as a threat.
Windows just couldn't access the file because Avast put it in quarantine.
I think that Windows Defender is disabled in your system, for as long as Avast is active.

Anyway, these false positives is an Avast bug, not KOHighlights.
By this I mean that, there is nothing I can do to fix such a problem, other than to suggest that you [report this false positive to them](https://businesshelp.avast.com/Content/Products/General_Help/SampleSubmission/SubmittingFalsePositives.htm).

Of course I also assume that you downloaded the file from [GiHub's releases](https://github.com/noembryo/KoHighlights/releases) or [my site](http://www.noembryo.com/apps.php?kohighlights) and not from a random internet place..

Thank you for the heads up though.. 🙏

**Comment by anoop249** [comment]
Hi 

Thank you for your comments in reply. 

The issue is resolved after i reported a false positive in AVAST. 

I was able to install the KOhighlights application afterwards

Thank you,

**Comment by noembryo** [comment]
Good to hear that your resolved the issue.. 🥳
